
databases:
  - name: meez
    plan: free
    databaseName: meez
    user: meez

services:
  - type: web
    name: meez
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: meez
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
